### ISSUE TITLE
An introduction and overview of GraphQL

### ISSUE THREAD

**Issue by patelg123** [leicesterjs/speakers#1]
Talk Title: GraphQL
Talk Time (rough estimate):
10 -15 minutes

Description:

Since it became open source in 2015, GraphQL has been enjoying a growing activity. It is used by teams of all sizes in many different environments and languages to power mobile apps, websites, and APIs. Famous companies such as Facebook, Twitter, Yelp, Pinterest, and Coursera rely on GraphQL for their platforms.

This talk is an introduction to GraphQL and the advantages it has over REST API calls.

**Comment by joshghent** [comment]
Hi @patelg123, apologies for not getting back to you. This sounds great! I'd love to hear a talk on graphql (because I know nothing about it). When would you be available to do this talk?
We have our next event booked, and then we probably won't have a December event so how about January?

**Comment by patelg123** [comment]
Hi Josh,

January should be okay. I'll chat to you later on this evening regarding
this anyway.

Catch you later,

Girish

**Comment by joshghent** [comment]
@patelg123 Brilliant, yes we will discuss it later at the meetup 👍

**Comment by joshghent** [comment]
Thank you again @patelg123 - was a great talk. Hope to have you back soon
