### ISSUE TITLE
Embedded JS - Just when you thought you'd have to learn C

### ISSUE THREAD

**Issue by dave-irvine** [leicesterjs/speakers#2]
Talk Title: Embedded JS - Just when you thought you'd have to learn C
Talk Time (rough estimate): Yes

Description:

One day, an evil genius (Gordon Williams) decided to put JavaScript on a Microcontroller, called it Espruino and released it to the world. Shortly afterwards, a crazy idiot who has no business being anywhere near a microcontroller decided to see what he could do with it. I am that crazy idiot. This is Embedded JS.

**Comment by joshghent** [comment]
Thanks for this @dave-irvine - sounds very interesting.
Talk time is fairly flexible 15-30 minutes. Let us know if you need anything in particular for this event or want people to bring their laptops?

Shall I pencil you in for January? Quite a while away but confirm with me when you can 👍 Look forward to this

**Comment by joshghent** [comment]
Thanks again @dave-irvine - got awesome feedback about this one. Would love to have you back soon 👍
