### ISSUE TITLE
Exploring JAMStack

### ISSUE THREAD

**Issue by pmuston** [leicesterjs/speakers#3]
Talk Title: Exploring the JAM Stack Ecosystem

Talk Time (rough estimate): 20mins

Twitter URL:
https://twitter.com/pmuston

Description:
The JAMStack is a radical new approach to building sites and web apps. It exposed me to a whole ecosystem that previously I had been unaware. In this talk I will explore the typical reasons that people use the JamStack - better performance; higher security; and cheaper, easier scaling. Beyond that, I found when diving deeper was better developer experience - an attempt for radically consistency and best of all a massive reduction in backend work.
I came came across JAMStack when recently rebuilding web sites for a series of best selling technical books and then switched implementations to use the JAMStack. Even if you've heard of the JAMStack before, don't think static sites, my use of realtime web components facilitating interactive workshops for one of the books may surprise you.

**Comment by joshghent** [comment]
Hi Paul, 

This looks great, thank you very much for your submission. We would love to have you give this talk.
We have a free slot in our February meetup which will take place on the 21st Feb, does this work for you?

**Comment by pmuston** [comment]
Yes that works for me.

**Comment by joshghent** [comment]
Hi @pmuston, just an update, because of a company meeting, I've had to move the date of the next event to the Thursday 28th February - is this still ok for you?

**Comment by joshghent** [comment]
Hey @pmuston - hope you're well. Can I pencil you in still for 28th Feb?

**Comment by pmuston** [comment]
Hi Josh,

I totally missed your previous message. That should be fine.

Paul

**Comment by joshghent** [comment]
Hi @pmuston, wanted to confirm you're still ok for next week (Thurs 28th Feb). Looking forward to this talk - will be a great one 👍

**Comment by pmuston** [comment]
Yep. All ok.

**Comment by joshghent** [comment]
Thank you again for speaking at LeicesterJS, we look forward to seeing you soon 👍
