### ISSUE TITLE
Delivering JS at Scale - CompareTheMarket

### ISSUE THREAD

**Issue by TomFoyster** [leicesterjs/speakers#4]
Talk Title: Delivering JS at Scale

Talk Time (rough estimate): 20 - 25 minutes

Twitter URL:

Description:
A look into the challenges we've faced, and the things we've learnt, when working with hundreds of developers to deliver to millions of users.

**Comment by joshghent** [comment]
Thanks again @TomFoyster for this, it was fantastic!
