### ISSUE TITLE
How to think like a Security Engineer

### ISSUE THREAD

**Issue by mozmark** [leicesterjs/speakers#5]
Talk Title:
How to think like a Security Engineer

Talk Time (rough estimate):
20 mins, if that's what you want.

Do you want help preparing the talk?: 
No, thanks.

Twitter URL:
https://mobile.twitter.com/mr_goodwin

Description:
We all view systems differently. This talk examines how security specialists (builders, attackers and defenders) might see yours... and how that can help you build more secure systems.

**Comment by joshghent** [comment]
Hey Mark, would be a privilege to have you down to speak! We have a free slot in April or May if that works? We're a bit booked up until then! 

Also if you need any assistance covering transport costs then please let me know and I can get this arranged.

**Comment by mozmark** [comment]
Let me know the dates in April and May and I'll check my calendar.

If it's on a day when I'm working in London then I should be able to split my rail journey for no extra cost. And if not, maybe Mozilla will support anyway. And you provide Pizza, right?

**Comment by joshghent** [comment]
Hi @mozmark 
April's will be 16th
May's will be 21st - both of them are Thursdays.

Ok perfect, let me know either way or if Mozilla wants to split the costs.

Yes of course we provide pizza, we wouldn't be a meetup without it! Closer to the time, you can let me know your favourite topping so we can get that in 👍 🍕

**Comment by joshghent** [comment]
Thanks for giving this talk @mozmark!
